version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    ports:
      - '80:4200'
    volumes:
      - vms-frontend-sync:/app:nocopy
      - node_modules:/app/node_modules
      
      
volumes:
  vms-frontend-sync:
    external: true
  node_modules: