version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile.init
    env_file: ../.env
    ports:
      - '80:4200'
    volumes:
      - app-sync:/app:nocopy
      - node_modules:/app/node_modules

volumes:
  app-sync:
    external: true
  node_modules: