version: "3"

services:
  app:
    build:
      context: ../../
      dockerfile: docker/prod-sv/Dockerfile
    ports:
      - "8085:80"
    volumes:
      - ../../app/dist/browser/sv:/usr/share/nginx/html
